name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Navigate to the workspace directory to build and test
    - name: Navigate to Workspace
      run: cd RustPyNetWorkspace

    - name: Build
      run: cargo build --workspace --verbose

    # Navigate back to the root directory to run tests outside the workspace
    - name: Navigate to Root
      run: cd ..

    # Run tests from the rustpynet_test directory
    - name: Run rustpynet_test tests
      run: |
        cd rustpynet_test
        cargo test --verbose
